# Generated by Django 5.0.4 on 2024-05-08 12:06

import train_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_api.utils.train_image_path
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="num_seats",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.IntegerField(null=True),
        ),
    ]
