# Generated by Django 5.0.3 on 2024-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_api", "0003_alter_journey_route_alter_journey_train_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="crews",
            field=models.ManyToManyField(related_name="journeys", to="train_api.crew"),
        ),
    ]
